<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="37901" started-at="2020-12-04T14:11:41Z" finished-at="2020-12-04T14:12:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="37901" started-at="2020-12-04T14:11:41Z" finished-at="2020-12-04T14:12:19Z">
      <class name="com.visionit.orangehrm.testCases.Login_Tc_001">
        <test-method status="PASS" signature="setupSuite()[pri:0, instance:com.visionit.orangehrm.testCases.Login_Tc_001@29774679]" name="setupSuite" is-config="true" duration-ms="2938" started-at="2020-12-04T19:41:38Z" finished-at="2020-12-04T19:41:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method status="PASS" signature="setupExtent()[pri:0, instance:com.visionit.orangehrm.testCases.Login_Tc_001@29774679]" name="setupExtent" is-config="true" duration-ms="797" started-at="2020-12-04T19:41:41Z" finished-at="2020-12-04T19:41:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupExtent -->
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.visionit.orangehrm.testCases.Login_Tc_001@29774679]" name="setUp" is-config="true" duration-ms="22241" started-at="2020-12-04T19:41:42Z" finished-at="2020-12-04T19:42:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginOrangeHrmTest()[pri:0, instance:com.visionit.orangehrm.testCases.Login_Tc_001@29774679]" name="loginOrangeHrmTest" duration-ms="8913" started-at="2020-12-04T19:42:04Z" finished-at="2020-12-04T19:42:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.visionit.orangehrm.testCases.Login_Tc_001.loginOrangeHrmTest(Login_Tc_001.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginOrangeHrmTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.visionit.orangehrm.testCases.Login_Tc_001@29774679]" name="tearDown" is-config="true" duration-ms="3913" started-at="2020-12-04T19:42:13Z" finished-at="2020-12-04T19:42:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginOrangeHrmTest status=FAILURE method=Login_Tc_001.loginOrangeHrmTest()[pri:0, instance:com.visionit.orangehrm.testCases.Login_Tc_001@29774679] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.visionit.orangehrm.testCases.Login_Tc_001@29774679]" name="endReport" is-config="true" duration-ms="1969" started-at="2020-12-04T19:42:17Z" finished-at="2020-12-04T19:42:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.visionit.orangehrm.testCases.Login_Tc_001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
